services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: forgeai-postgres
    environment:
      POSTGRES_DB: forgeai_omega
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forgeai-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: forgeai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - forgeai-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  forgeai-network:
    driver: bridge
